/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FreePlacementTestRouteImport } from './routes/free-placement-test'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlacementTestLeadIdRouteImport } from './routes/placement-test.$leadId'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as ApiPublicPlacementSubmitRouteImport } from './routes/api/public/placement/submit'
import { Route as ApiPublicPlacementStateRouteImport } from './routes/api/public/placement/state'
import { Route as ApiPublicPlacementStartRouteImport } from './routes/api/public/placement/start'
import { Route as ApiPublicPlacementNextRouteImport } from './routes/api/public/placement/next'
import { Route as AuthenticatedDashboardAttemptsAttemptIdRouteImport } from './routes/_authenticated/dashboard.attempts.$attemptId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FreePlacementTestRoute = FreePlacementTestRouteImport.update({
  id: '/free-placement-test',
  path: '/free-placement-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementTestLeadIdRoute = PlacementTestLeadIdRouteImport.update({
  id: '/placement-test/$leadId',
  path: '/placement-test/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlacementSubmitRoute =
  ApiPublicPlacementSubmitRouteImport.update({
    id: '/api/public/placement/submit',
    path: '/api/public/placement/submit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPlacementStateRoute = ApiPublicPlacementStateRouteImport.update({
  id: '/api/public/placement/state',
  path: '/api/public/placement/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlacementStartRoute = ApiPublicPlacementStartRouteImport.update({
  id: '/api/public/placement/start',
  path: '/api/public/placement/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlacementNextRoute = ApiPublicPlacementNextRouteImport.update({
  id: '/api/public/placement/next',
  path: '/api/public/placement/next',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardAttemptsAttemptIdRoute =
  AuthenticatedDashboardAttemptsAttemptIdRouteImport.update({
    id: '/attempts/$attemptId',
    path: '/attempts/$attemptId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/free-placement-test': typeof FreePlacementTestRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/placement-test/$leadId': typeof PlacementTestLeadIdRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/dashboard/attempts/$attemptId': typeof AuthenticatedDashboardAttemptsAttemptIdRoute
  '/api/public/placement/next': typeof ApiPublicPlacementNextRoute
  '/api/public/placement/start': typeof ApiPublicPlacementStartRoute
  '/api/public/placement/state': typeof ApiPublicPlacementStateRoute
  '/api/public/placement/submit': typeof ApiPublicPlacementSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/free-placement-test': typeof FreePlacementTestRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/placement-test/$leadId': typeof PlacementTestLeadIdRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/dashboard/attempts/$attemptId': typeof AuthenticatedDashboardAttemptsAttemptIdRoute
  '/api/public/placement/next': typeof ApiPublicPlacementNextRoute
  '/api/public/placement/start': typeof ApiPublicPlacementStartRoute
  '/api/public/placement/state': typeof ApiPublicPlacementStateRoute
  '/api/public/placement/submit': typeof ApiPublicPlacementSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/free-placement-test': typeof FreePlacementTestRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/placement-test/$leadId': typeof PlacementTestLeadIdRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/_authenticated/dashboard/attempts/$attemptId': typeof AuthenticatedDashboardAttemptsAttemptIdRoute
  '/api/public/placement/next': typeof ApiPublicPlacementNextRoute
  '/api/public/placement/start': typeof ApiPublicPlacementStartRoute
  '/api/public/placement/state': typeof ApiPublicPlacementStateRoute
  '/api/public/placement/submit': typeof ApiPublicPlacementSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/free-placement-test'
    | '/privacy'
    | '/reset-password'
    | '/dashboard'
    | '/placement-test/$leadId'
    | '/api/public/leads'
    | '/dashboard/attempts/$attemptId'
    | '/api/public/placement/next'
    | '/api/public/placement/start'
    | '/api/public/placement/state'
    | '/api/public/placement/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/free-placement-test'
    | '/privacy'
    | '/reset-password'
    | '/dashboard'
    | '/placement-test/$leadId'
    | '/api/public/leads'
    | '/dashboard/attempts/$attemptId'
    | '/api/public/placement/next'
    | '/api/public/placement/start'
    | '/api/public/placement/state'
    | '/api/public/placement/submit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/free-placement-test'
    | '/privacy'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/placement-test/$leadId'
    | '/api/public/leads'
    | '/_authenticated/dashboard/attempts/$attemptId'
    | '/api/public/placement/next'
    | '/api/public/placement/start'
    | '/api/public/placement/state'
    | '/api/public/placement/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FreePlacementTestRoute: typeof FreePlacementTestRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PlacementTestLeadIdRoute: typeof PlacementTestLeadIdRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiPublicPlacementNextRoute: typeof ApiPublicPlacementNextRoute
  ApiPublicPlacementStartRoute: typeof ApiPublicPlacementStartRoute
  ApiPublicPlacementStateRoute: typeof ApiPublicPlacementStateRoute
  ApiPublicPlacementSubmitRoute: typeof ApiPublicPlacementSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-placement-test': {
      id: '/free-placement-test'
      path: '/free-placement-test'
      fullPath: '/free-placement-test'
      preLoaderRoute: typeof FreePlacementTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement-test/$leadId': {
      id: '/placement-test/$leadId'
      path: '/placement-test/$leadId'
      fullPath: '/placement-test/$leadId'
      preLoaderRoute: typeof PlacementTestLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/placement/submit': {
      id: '/api/public/placement/submit'
      path: '/api/public/placement/submit'
      fullPath: '/api/public/placement/submit'
      preLoaderRoute: typeof ApiPublicPlacementSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/placement/state': {
      id: '/api/public/placement/state'
      path: '/api/public/placement/state'
      fullPath: '/api/public/placement/state'
      preLoaderRoute: typeof ApiPublicPlacementStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/placement/start': {
      id: '/api/public/placement/start'
      path: '/api/public/placement/start'
      fullPath: '/api/public/placement/start'
      preLoaderRoute: typeof ApiPublicPlacementStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/placement/next': {
      id: '/api/public/placement/next'
      path: '/api/public/placement/next'
      fullPath: '/api/public/placement/next'
      preLoaderRoute: typeof ApiPublicPlacementNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/attempts/$attemptId': {
      id: '/_authenticated/dashboard/attempts/$attemptId'
      path: '/attempts/$attemptId'
      fullPath: '/dashboard/attempts/$attemptId'
      preLoaderRoute: typeof AuthenticatedDashboardAttemptsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAttemptsAttemptIdRoute: typeof AuthenticatedDashboardAttemptsAttemptIdRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAttemptsAttemptIdRoute:
      AuthenticatedDashboardAttemptsAttemptIdRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FreePlacementTestRoute: FreePlacementTestRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PlacementTestLeadIdRoute: PlacementTestLeadIdRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiPublicPlacementNextRoute: ApiPublicPlacementNextRoute,
  ApiPublicPlacementStartRoute: ApiPublicPlacementStartRoute,
  ApiPublicPlacementStateRoute: ApiPublicPlacementStateRoute,
  ApiPublicPlacementSubmitRoute: ApiPublicPlacementSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
