/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FreePlacementTestRouteImport } from './routes/free-placement-test'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlacementTestLeadIdRouteImport } from './routes/placement-test.$leadId'
import { Route as GrammarTestLeadIdRouteImport } from './routes/grammar-test.$leadId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as ApiPublicCourseInquiryRouteImport } from './routes/api/public/course-inquiry'
import { Route as AuthenticatedTeacherStudentIdRouteImport } from './routes/_authenticated/teacher_.$studentId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin.companies'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as ApiPublicPlacementSubmitRouteImport } from './routes/api/public/placement/submit'
import { Route as ApiPublicPlacementStateRouteImport } from './routes/api/public/placement/state'
import { Route as ApiPublicPlacementStartRouteImport } from './routes/api/public/placement/start'
import { Route as ApiPublicPlacementNextRouteImport } from './routes/api/public/placement/next'
import { Route as ApiPublicGrammarSubmitRouteImport } from './routes/api/public/grammar/submit'
import { Route as ApiPublicGrammarStateRouteImport } from './routes/api/public/grammar/state'
import { Route as ApiPublicGrammarStartRouteImport } from './routes/api/public/grammar/start'
import { Route as ApiPublicGrammarPracticeMistakesRouteImport } from './routes/api/public/grammar/practice-mistakes'
import { Route as ApiPublicGrammarNextRouteImport } from './routes/api/public/grammar/next'
import { Route as AuthenticatedDashboardAttemptsAttemptIdRouteImport } from './routes/_authenticated/dashboard_.attempts.$attemptId'
import { Route as AuthenticatedAdminCoursesCourseIdRouteImport } from './routes/_authenticated/admin.courses_.$courseId'
import { Route as AuthenticatedAdminBlogPostIdRouteImport } from './routes/_authenticated/admin.blog_.$postId'
import { Route as AuthenticatedTeacherStudentIdAttemptsAttemptIdRouteImport } from './routes/_authenticated/teacher_.$studentId_.attempts.$attemptId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FreePlacementTestRoute = FreePlacementTestRouteImport.update({
  id: '/free-placement-test',
  path: '/free-placement-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementTestLeadIdRoute = PlacementTestLeadIdRouteImport.update({
  id: '/placement-test/$leadId',
  path: '/placement-test/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarTestLeadIdRoute = GrammarTestLeadIdRouteImport.update({
  id: '/grammar-test/$leadId',
  path: '/grammar-test/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCourseInquiryRoute = ApiPublicCourseInquiryRouteImport.update({
  id: '/api/public/course-inquiry',
  path: '/api/public/course-inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherStudentIdRoute =
  AuthenticatedTeacherStudentIdRouteImport.update({
    id: '/teacher_/$studentId',
    path: '/teacher/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicPlacementSubmitRoute =
  ApiPublicPlacementSubmitRouteImport.update({
    id: '/api/public/placement/submit',
    path: '/api/public/placement/submit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPlacementStateRoute = ApiPublicPlacementStateRouteImport.update({
  id: '/api/public/placement/state',
  path: '/api/public/placement/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlacementStartRoute = ApiPublicPlacementStartRouteImport.update({
  id: '/api/public/placement/start',
  path: '/api/public/placement/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlacementNextRoute = ApiPublicPlacementNextRouteImport.update({
  id: '/api/public/placement/next',
  path: '/api/public/placement/next',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGrammarSubmitRoute = ApiPublicGrammarSubmitRouteImport.update({
  id: '/api/public/grammar/submit',
  path: '/api/public/grammar/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGrammarStateRoute = ApiPublicGrammarStateRouteImport.update({
  id: '/api/public/grammar/state',
  path: '/api/public/grammar/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGrammarStartRoute = ApiPublicGrammarStartRouteImport.update({
  id: '/api/public/grammar/start',
  path: '/api/public/grammar/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGrammarPracticeMistakesRoute =
  ApiPublicGrammarPracticeMistakesRouteImport.update({
    id: '/api/public/grammar/practice-mistakes',
    path: '/api/public/grammar/practice-mistakes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrammarNextRoute = ApiPublicGrammarNextRouteImport.update({
  id: '/api/public/grammar/next',
  path: '/api/public/grammar/next',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardAttemptsAttemptIdRoute =
  AuthenticatedDashboardAttemptsAttemptIdRouteImport.update({
    id: '/dashboard_/attempts/$attemptId',
    path: '/dashboard/attempts/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCoursesCourseIdRoute =
  AuthenticatedAdminCoursesCourseIdRouteImport.update({
    id: '/courses_/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogPostIdRoute =
  AuthenticatedAdminBlogPostIdRouteImport.update({
    id: '/blog_/$postId',
    path: '/blog/$postId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedTeacherStudentIdAttemptsAttemptIdRoute =
  AuthenticatedTeacherStudentIdAttemptsAttemptIdRouteImport.update({
    id: '/teacher_/$studentId_/attempts/$attemptId',
    path: '/teacher/$studentId/attempts/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/free-placement-test': typeof FreePlacementTestRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/grammar-test/$leadId': typeof GrammarTestLeadIdRoute
  '/placement-test/$leadId': typeof PlacementTestLeadIdRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/teacher/$studentId': typeof AuthenticatedTeacherStudentIdRoute
  '/api/public/course-inquiry': typeof ApiPublicCourseInquiryRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/admin/blog/$postId': typeof AuthenticatedAdminBlogPostIdRoute
  '/admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/dashboard/attempts/$attemptId': typeof AuthenticatedDashboardAttemptsAttemptIdRoute
  '/api/public/grammar/next': typeof ApiPublicGrammarNextRoute
  '/api/public/grammar/practice-mistakes': typeof ApiPublicGrammarPracticeMistakesRoute
  '/api/public/grammar/start': typeof ApiPublicGrammarStartRoute
  '/api/public/grammar/state': typeof ApiPublicGrammarStateRoute
  '/api/public/grammar/submit': typeof ApiPublicGrammarSubmitRoute
  '/api/public/placement/next': typeof ApiPublicPlacementNextRoute
  '/api/public/placement/start': typeof ApiPublicPlacementStartRoute
  '/api/public/placement/state': typeof ApiPublicPlacementStateRoute
  '/api/public/placement/submit': typeof ApiPublicPlacementSubmitRoute
  '/teacher/$studentId/attempts/$attemptId': typeof AuthenticatedTeacherStudentIdAttemptsAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/free-placement-test': typeof FreePlacementTestRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/grammar-test/$leadId': typeof GrammarTestLeadIdRoute
  '/placement-test/$leadId': typeof PlacementTestLeadIdRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/teacher/$studentId': typeof AuthenticatedTeacherStudentIdRoute
  '/api/public/course-inquiry': typeof ApiPublicCourseInquiryRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/admin/blog/$postId': typeof AuthenticatedAdminBlogPostIdRoute
  '/admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/dashboard/attempts/$attemptId': typeof AuthenticatedDashboardAttemptsAttemptIdRoute
  '/api/public/grammar/next': typeof ApiPublicGrammarNextRoute
  '/api/public/grammar/practice-mistakes': typeof ApiPublicGrammarPracticeMistakesRoute
  '/api/public/grammar/start': typeof ApiPublicGrammarStartRoute
  '/api/public/grammar/state': typeof ApiPublicGrammarStateRoute
  '/api/public/grammar/submit': typeof ApiPublicGrammarSubmitRoute
  '/api/public/placement/next': typeof ApiPublicPlacementNextRoute
  '/api/public/placement/start': typeof ApiPublicPlacementStartRoute
  '/api/public/placement/state': typeof ApiPublicPlacementStateRoute
  '/api/public/placement/submit': typeof ApiPublicPlacementSubmitRoute
  '/teacher/$studentId/attempts/$attemptId': typeof AuthenticatedTeacherStudentIdAttemptsAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/free-placement-test': typeof FreePlacementTestRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/grammar-test/$leadId': typeof GrammarTestLeadIdRoute
  '/placement-test/$leadId': typeof PlacementTestLeadIdRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/teacher_/$studentId': typeof AuthenticatedTeacherStudentIdRoute
  '/api/public/course-inquiry': typeof ApiPublicCourseInquiryRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/_authenticated/admin/blog_/$postId': typeof AuthenticatedAdminBlogPostIdRoute
  '/_authenticated/admin/courses_/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/_authenticated/dashboard_/attempts/$attemptId': typeof AuthenticatedDashboardAttemptsAttemptIdRoute
  '/api/public/grammar/next': typeof ApiPublicGrammarNextRoute
  '/api/public/grammar/practice-mistakes': typeof ApiPublicGrammarPracticeMistakesRoute
  '/api/public/grammar/start': typeof ApiPublicGrammarStartRoute
  '/api/public/grammar/state': typeof ApiPublicGrammarStateRoute
  '/api/public/grammar/submit': typeof ApiPublicGrammarSubmitRoute
  '/api/public/placement/next': typeof ApiPublicPlacementNextRoute
  '/api/public/placement/start': typeof ApiPublicPlacementStartRoute
  '/api/public/placement/state': typeof ApiPublicPlacementStateRoute
  '/api/public/placement/submit': typeof ApiPublicPlacementSubmitRoute
  '/_authenticated/teacher_/$studentId_/attempts/$attemptId': typeof AuthenticatedTeacherStudentIdAttemptsAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/free-placement-test'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/teacher'
    | '/blog/$slug'
    | '/grammar-test/$leadId'
    | '/placement-test/$leadId'
    | '/admin/blog'
    | '/admin/companies'
    | '/admin/courses'
    | '/admin/users'
    | '/teacher/$studentId'
    | '/api/public/course-inquiry'
    | '/api/public/leads'
    | '/admin/blog/$postId'
    | '/admin/courses/$courseId'
    | '/dashboard/attempts/$attemptId'
    | '/api/public/grammar/next'
    | '/api/public/grammar/practice-mistakes'
    | '/api/public/grammar/start'
    | '/api/public/grammar/state'
    | '/api/public/grammar/submit'
    | '/api/public/placement/next'
    | '/api/public/placement/start'
    | '/api/public/placement/state'
    | '/api/public/placement/submit'
    | '/teacher/$studentId/attempts/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/free-placement-test'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/teacher'
    | '/blog/$slug'
    | '/grammar-test/$leadId'
    | '/placement-test/$leadId'
    | '/admin/blog'
    | '/admin/companies'
    | '/admin/courses'
    | '/admin/users'
    | '/teacher/$studentId'
    | '/api/public/course-inquiry'
    | '/api/public/leads'
    | '/admin/blog/$postId'
    | '/admin/courses/$courseId'
    | '/dashboard/attempts/$attemptId'
    | '/api/public/grammar/next'
    | '/api/public/grammar/practice-mistakes'
    | '/api/public/grammar/start'
    | '/api/public/grammar/state'
    | '/api/public/grammar/submit'
    | '/api/public/placement/next'
    | '/api/public/placement/start'
    | '/api/public/placement/state'
    | '/api/public/placement/submit'
    | '/teacher/$studentId/attempts/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/free-placement-test'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/teacher'
    | '/blog/$slug'
    | '/grammar-test/$leadId'
    | '/placement-test/$leadId'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/users'
    | '/_authenticated/teacher_/$studentId'
    | '/api/public/course-inquiry'
    | '/api/public/leads'
    | '/_authenticated/admin/blog_/$postId'
    | '/_authenticated/admin/courses_/$courseId'
    | '/_authenticated/dashboard_/attempts/$attemptId'
    | '/api/public/grammar/next'
    | '/api/public/grammar/practice-mistakes'
    | '/api/public/grammar/start'
    | '/api/public/grammar/state'
    | '/api/public/grammar/submit'
    | '/api/public/placement/next'
    | '/api/public/placement/start'
    | '/api/public/placement/state'
    | '/api/public/placement/submit'
    | '/_authenticated/teacher_/$studentId_/attempts/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FreePlacementTestRoute: typeof FreePlacementTestRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GrammarTestLeadIdRoute: typeof GrammarTestLeadIdRoute
  PlacementTestLeadIdRoute: typeof PlacementTestLeadIdRoute
  ApiPublicCourseInquiryRoute: typeof ApiPublicCourseInquiryRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiPublicGrammarNextRoute: typeof ApiPublicGrammarNextRoute
  ApiPublicGrammarPracticeMistakesRoute: typeof ApiPublicGrammarPracticeMistakesRoute
  ApiPublicGrammarStartRoute: typeof ApiPublicGrammarStartRoute
  ApiPublicGrammarStateRoute: typeof ApiPublicGrammarStateRoute
  ApiPublicGrammarSubmitRoute: typeof ApiPublicGrammarSubmitRoute
  ApiPublicPlacementNextRoute: typeof ApiPublicPlacementNextRoute
  ApiPublicPlacementStartRoute: typeof ApiPublicPlacementStartRoute
  ApiPublicPlacementStateRoute: typeof ApiPublicPlacementStateRoute
  ApiPublicPlacementSubmitRoute: typeof ApiPublicPlacementSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-placement-test': {
      id: '/free-placement-test'
      path: '/free-placement-test'
      fullPath: '/free-placement-test'
      preLoaderRoute: typeof FreePlacementTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement-test/$leadId': {
      id: '/placement-test/$leadId'
      path: '/placement-test/$leadId'
      fullPath: '/placement-test/$leadId'
      preLoaderRoute: typeof PlacementTestLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar-test/$leadId': {
      id: '/grammar-test/$leadId'
      path: '/grammar-test/$leadId'
      fullPath: '/grammar-test/$leadId'
      preLoaderRoute: typeof GrammarTestLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/course-inquiry': {
      id: '/api/public/course-inquiry'
      path: '/api/public/course-inquiry'
      fullPath: '/api/public/course-inquiry'
      preLoaderRoute: typeof ApiPublicCourseInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher_/$studentId': {
      id: '/_authenticated/teacher_/$studentId'
      path: '/teacher/$studentId'
      fullPath: '/teacher/$studentId'
      preLoaderRoute: typeof AuthenticatedTeacherStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/placement/submit': {
      id: '/api/public/placement/submit'
      path: '/api/public/placement/submit'
      fullPath: '/api/public/placement/submit'
      preLoaderRoute: typeof ApiPublicPlacementSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/placement/state': {
      id: '/api/public/placement/state'
      path: '/api/public/placement/state'
      fullPath: '/api/public/placement/state'
      preLoaderRoute: typeof ApiPublicPlacementStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/placement/start': {
      id: '/api/public/placement/start'
      path: '/api/public/placement/start'
      fullPath: '/api/public/placement/start'
      preLoaderRoute: typeof ApiPublicPlacementStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/placement/next': {
      id: '/api/public/placement/next'
      path: '/api/public/placement/next'
      fullPath: '/api/public/placement/next'
      preLoaderRoute: typeof ApiPublicPlacementNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/grammar/submit': {
      id: '/api/public/grammar/submit'
      path: '/api/public/grammar/submit'
      fullPath: '/api/public/grammar/submit'
      preLoaderRoute: typeof ApiPublicGrammarSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/grammar/state': {
      id: '/api/public/grammar/state'
      path: '/api/public/grammar/state'
      fullPath: '/api/public/grammar/state'
      preLoaderRoute: typeof ApiPublicGrammarStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/grammar/start': {
      id: '/api/public/grammar/start'
      path: '/api/public/grammar/start'
      fullPath: '/api/public/grammar/start'
      preLoaderRoute: typeof ApiPublicGrammarStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/grammar/practice-mistakes': {
      id: '/api/public/grammar/practice-mistakes'
      path: '/api/public/grammar/practice-mistakes'
      fullPath: '/api/public/grammar/practice-mistakes'
      preLoaderRoute: typeof ApiPublicGrammarPracticeMistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/grammar/next': {
      id: '/api/public/grammar/next'
      path: '/api/public/grammar/next'
      fullPath: '/api/public/grammar/next'
      preLoaderRoute: typeof ApiPublicGrammarNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard_/attempts/$attemptId': {
      id: '/_authenticated/dashboard_/attempts/$attemptId'
      path: '/dashboard/attempts/$attemptId'
      fullPath: '/dashboard/attempts/$attemptId'
      preLoaderRoute: typeof AuthenticatedDashboardAttemptsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/courses_/$courseId': {
      id: '/_authenticated/admin/courses_/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog_/$postId': {
      id: '/_authenticated/admin/blog_/$postId'
      path: '/blog/$postId'
      fullPath: '/admin/blog/$postId'
      preLoaderRoute: typeof AuthenticatedAdminBlogPostIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/teacher_/$studentId_/attempts/$attemptId': {
      id: '/_authenticated/teacher_/$studentId_/attempts/$attemptId'
      path: '/teacher/$studentId/attempts/$attemptId'
      fullPath: '/teacher/$studentId/attempts/$attemptId'
      preLoaderRoute: typeof AuthenticatedTeacherStudentIdAttemptsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminBlogPostIdRoute: typeof AuthenticatedAdminBlogPostIdRoute
  AuthenticatedAdminCoursesCourseIdRoute: typeof AuthenticatedAdminCoursesCourseIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminBlogPostIdRoute: AuthenticatedAdminBlogPostIdRoute,
  AuthenticatedAdminCoursesCourseIdRoute:
    AuthenticatedAdminCoursesCourseIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRoute
  AuthenticatedTeacherStudentIdRoute: typeof AuthenticatedTeacherStudentIdRoute
  AuthenticatedDashboardAttemptsAttemptIdRoute: typeof AuthenticatedDashboardAttemptsAttemptIdRoute
  AuthenticatedTeacherStudentIdAttemptsAttemptIdRoute: typeof AuthenticatedTeacherStudentIdAttemptsAttemptIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRoute,
  AuthenticatedTeacherStudentIdRoute: AuthenticatedTeacherStudentIdRoute,
  AuthenticatedDashboardAttemptsAttemptIdRoute:
    AuthenticatedDashboardAttemptsAttemptIdRoute,
  AuthenticatedTeacherStudentIdAttemptsAttemptIdRoute:
    AuthenticatedTeacherStudentIdAttemptsAttemptIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FreePlacementTestRoute: FreePlacementTestRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  GrammarTestLeadIdRoute: GrammarTestLeadIdRoute,
  PlacementTestLeadIdRoute: PlacementTestLeadIdRoute,
  ApiPublicCourseInquiryRoute: ApiPublicCourseInquiryRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiPublicGrammarNextRoute: ApiPublicGrammarNextRoute,
  ApiPublicGrammarPracticeMistakesRoute: ApiPublicGrammarPracticeMistakesRoute,
  ApiPublicGrammarStartRoute: ApiPublicGrammarStartRoute,
  ApiPublicGrammarStateRoute: ApiPublicGrammarStateRoute,
  ApiPublicGrammarSubmitRoute: ApiPublicGrammarSubmitRoute,
  ApiPublicPlacementNextRoute: ApiPublicPlacementNextRoute,
  ApiPublicPlacementStartRoute: ApiPublicPlacementStartRoute,
  ApiPublicPlacementStateRoute: ApiPublicPlacementStateRoute,
  ApiPublicPlacementSubmitRoute: ApiPublicPlacementSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
